### ISSUE TITLE
Export world or extract

### ISSUE THREAD

**Issue by sils** [reverie/yourworldoftext#6]
Would be neat to be able to export it somehow so it can be used for notetaking etc.

**Comment by reverie** [comment]
1. Go to the configuration page for your world. The URL looks like http://www.yourworldoftext.com/accounts/configure/~andrew/example.
2. Replace "configure" with "printable", like http://www.yourworldoftext.com/accounts/printable/~andrew/example

This only works for smaller worlds for now...

**Comment by sils** [comment]
CC @chauffer

**Comment by sils** [comment]
Thanks so much! Awesome thing :)

**Comment by reverie** [comment]
You're welcome! :)
