### ISSUE TITLE
is this an older version

### ISSUE THREAD

**Issue by PacificBlackDuck** [reverie/yourworldoftext#7]
is this version older than the one on https://yourworldoftext.com
the one i have:
![image](https://user-images.githubusercontent.com/20697185/27001749-8edc8f0a-4e14-11e7-87ca-5cbe2199127d.png)
the one on https://yourworldoftext.com :
![image](https://user-images.githubusercontent.com/20697185/27001760-af19d336-4e14-11e7-9b52-330640d88272.png)
or am i doing something wrong?

**Comment by reverie** [comment]
Yes

**Comment by PacificBlackDuck** [comment]
any plans of updating the code on github?

**Comment by reverie** [comment]
Probably not, sorry
